// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5474.Orion.subsystems;

import org.usfirst.frc5474.Orion.Robot;
import org.usfirst.frc5474.Orion.commands.arcadeDrive;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class driveSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Spark rightMotorPair;
    private Spark leftMotorPair;
    private DifferentialDrive diffDrive;
    public Encoder rightPairEncoder;
    public Encoder leftPairEncoder;
    public double compensationMult = 1;
    public double deltaDistance = 0;
    boolean compesationError = false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public driveSub() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightMotorPair = new Spark(8);
        addChild("rightMotorPair", rightMotorPair);
        rightMotorPair.setInverted(false);

        leftMotorPair = new Spark(9);
        addChild("leftMotorPair", leftMotorPair);
        leftMotorPair.setInverted(false);

        diffDrive = new DifferentialDrive(leftMotorPair, rightMotorPair);
        addChild("diffDrive", diffDrive);
        diffDrive.setSafetyEnabled(true);
        diffDrive.setExpiration(0.1);
        diffDrive.setMaxOutput(1.0);

        double encoderTickConstant = 1 / (60 / Math.PI); // gives approx 1in/1 encoder tick (CHECK YOUR MATH!)

        rightPairEncoder = new Encoder(6, 7, false);
        addChild("rightPairEncoder", rightPairEncoder);
        rightPairEncoder.setDistancePerPulse(1.0); // set twice?
        rightPairEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        // rightPairEncoder.setIndexSource(11, IndexingType.kResetOnRisingEdge);
        rightPairEncoder.setDistancePerPulse(encoderTickConstant);

        leftPairEncoder = new Encoder(8, 9, false);
        addChild("leftPairEncoder", leftPairEncoder);
        leftPairEncoder.setDistancePerPulse(1.0); // set twice?
        leftPairEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        // leftPairEncoder.setIndexSource(14, IndexingType.kResetOnRisingEdge);
        leftPairEncoder.setDistancePerPulse(encoderTickConstant);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new arcadeDrive());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void arcadeDrive(Joystick stick, Boolean straight) {
        if (!straight) {
            diffDrive.arcadeDrive(-stick.getY() * 0.75, stick.getRawAxis(4) * 0.7, true);
        } else {

            // =================================================
            SmartDashboard.putBoolean("Compensation Error!!!", compesationError);
            deltaDistance = leftPairEncoder.getDistance() / -rightPairEncoder.getDistance();
            // deltaDistance = currentLeftDistance/currentRightDistance;
            compensationMult = 1;
            // if((leftPairEncoder.getDistance() + rightPairEncoder.getDistance()) /2 > 10){
            compensationMult = (2 * (deltaDistance - 1)) + 1;
            if (compensationMult > 2 || compensationMult < .1) {
                compesationError = true;
                compensationMult = 1;
            } else {
                // compesationError = false;
            }
            // }
            SmartDashboard.putNumber("Compensation Multiplier (Left)", compensationMult);
            // compensationMult = deltaDistance + 1;
            // diffDrive.arcadeDrive(power, 0, true); //not sure what this line does
            leftMotorPair.set(-stick.getY() * 0.8); //diferent 0.8 that is needed to make less jittery
            rightMotorPair.set(stick.getY() * compensationMult * 0.8); //multiplied times 0.8; removed

        }
        // SmartDashboard.putNumber("x", stick.getX());
        // SmartDashboard.putNumber("y", stick.getY());
        SmartDashboard.putNumber("right distance", -rightPairEncoder.getDistance());
        SmartDashboard.putNumber("left distance", leftPairEncoder.getDistance());

        // =====================================================================================
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    public void driveStraight(double power) { // reset endoders before calling this
        // used for autonomous mode
        SmartDashboard.putBoolean("Compensation Error!!!", compesationError);
        deltaDistance = leftPairEncoder.getDistance() / -rightPairEncoder.getDistance();
        // deltaDistance = currentLeftDistance/currentRightDistance;
        compensationMult = 1;
        // if((leftPairEncoder.getDistance() + rightPairEncoder.getDistance()) /2 > 10){
        compensationMult = (4 * (deltaDistance - 1)) + 1;
        if (compensationMult > 1.5 || compensationMult < .5) {
            compesationError = true;
            compensationMult = 1;
        } else {
            compesationError = false;
        }
        // }
        SmartDashboard.putNumber("Compensation Multiplier (Left)", compensationMult);
        // compensationMult = deltaDistance + 1;
        // diffDrive.arcadeDrive(power, 0, true); //not sure what this line does

        // leftMotorPair.set(power);
        // rightMotorPair.set(-power * compensationMult * .80);
        leftMotorPair.set(-power * compensationMult);
        rightMotorPair.set(power);
    }

    public void turnRight(double power) {
        rightMotorPair.set(0);
        leftMotorPair.set(power);
    }

    public void turnLeft(double power) {
        leftMotorPair.set(0);
        rightMotorPair.set(power);
    }

    public void swivelRight(double power) {
        leftMotorPair.set(power);
        rightMotorPair.set(power);
    }

    public void swivelLeft(double power) {
        leftMotorPair.set(-power);
        rightMotorPair.set(-power);
    }

    public void stop() {
        // used for autonomous mode
        leftMotorPair.set(0);
        rightMotorPair.set(0);

    }

    public double GetandPutDistance() {
        double rightSideDistance = rightPairEncoder.getDistance();
        double leftSideDistance = leftPairEncoder.getDistance();
        double avgDistance = (rightSideDistance + leftSideDistance) / 2;
        return avgDistance;

        // diffDrive.arcadeDrive(0, 0, true);
    }

    public void resetEncoders() {
        Robot.driveSub.rightPairEncoder.reset();
        Robot.driveSub.leftPairEncoder.reset();

    }
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
