// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5474.Orion.subsystems;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class pGateSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private DoubleSolenoid gateSolenoid;
    private DoubleSolenoid pistonSolenoid;
    private DoubleSolenoid moveSlider;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public pGateSub() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        //clawCompressor = new Compressor(1);
        //addChild("clawCompressor",clawCompressor);
        //clawCompressor.setClosedLoopControl(true);
        
        //first parameter is node, CAN address of PCM
        gateSolenoid = new DoubleSolenoid(1, 0, 7);
        addChild("clawSolenoid",gateSolenoid);
        gateSolenoid.set(DoubleSolenoid.Value.kReverse);

        pistonSolenoid = new DoubleSolenoid(1, 1, 6);
        addChild("pistonSolenoid",pistonSolenoid);
        pistonSolenoid.set(DoubleSolenoid.Value.kReverse);

        moveSlider = new DoubleSolenoid(1, 2, 5);
        addChild("moveSlider",moveSlider);
        moveSlider.set(DoubleSolenoid.Value.kReverse);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        SmartDashboard.putNumber("piston up?", pistonSolenoid.getAll());
        //SmartDashboard.putBoolean("claw rev blacklist", clawSolenoid.isRevSolenoidBlackListed());
        //SmartDashboard.putBoolean("pusher rev blacklist", pushSolenoid.isRevSolenoidBlackListed());
        // Put code here to be run every loop

    }

    public void gateExtend() { //claw is closed
        //SmartDashboard.putString("", "piston extend");
        gateSolenoid.set(DoubleSolenoid.Value.kForward);
    }

    public void gateRetract() { //claw is open
        //SmartDashboard.putString("", "piston retract");
        gateSolenoid.set(DoubleSolenoid.Value.kReverse);
        //clawSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    public void pistonExtend() {
        pistonSolenoid.set(DoubleSolenoid.Value.kForward);
    }

    public void pistonRetract() {
        pistonSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    public void sliderExtend() {
        moveSlider.set(DoubleSolenoid.Value.kForward);
    }

    public void sliderRetract() {
        moveSlider.set(DoubleSolenoid.Value.kReverse);
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
//ground control to major tom (syncing test)

